# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.cache/wt [current_project]
set_property parent.project_path E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_output_repo e:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/MIPS_Parameters.v
set_property file_type "Verilog Header" [get_files E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/MIPS_Parameters.v]
read_verilog -library xil_defaultlib {
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Hazard.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Branch_Control.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/RegisterFile.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Register.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Mux4to1.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Mux2to1.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Mem_Control.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/MEMWB_Stage.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/IFID_Stage.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/IDEX_Stage.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Forwarding.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/EXMEM_Stage.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Control.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/Add.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/ALU.v
  E:/Education/DOAN/BaoCao/MIPS_Processor2/MIPS_Processor2.srcs/sources_1/new/CPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CPU -part xc7z020clg484-1


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
